### ISSUE TITLE
Any idea why this doesn't work for Docker 20?

### ISSUE THREAD

**Issue by Foovanadil** [bentolor/docker-dind-awscli#3] opened 2021-09-11 20:58 UTC
I am trying to use the new docker compose ecs features from a gitlab CI build and found my way over to this repo. This has been helpful to me in getting an image running with docker and the aws-cli but if I try to update to use `docker:20` instead of stable (which is currently 19) I get an error on the glibc install

`#6 4.420 /usr/glibc-compat/sbin/ldconfig: /usr/glibc-compat/lib/ld-linux-x86-64.so.2 is not a symbolic link`

Any ideas?

Thanks for publishing this source, it has been helpful for me.

**Comment by bentolor** [comment] 2021-09-12 07:15
This linker warning/error should also be present and should have no side-effect.

The real fix will be to fix the glibc package so that it has a symlink instead of a duplicate of the library. This appears to be an unintended consequence of the manual side-loading of the gcc library.

Are you seeing any other effects besides this warning during image build?

**Comment by bentolor** [comment] 2021-09-12 07:23
@Foovanadil Just found out, that there is a new Alpine GLIBC available which resolves this issue.

Thanks for bringing this issue to my attention.

**Closed** 2021-09-12 07:22 UTC
Labels: question

**Comment by bentolor** [comment] 2021-09-12 07:24
@Foovanadil  P.S.:  Just out of curiosity: Whats your motivation for v20 vs stable? Should I move forward to v20?

**Comment by Foovanadil** [comment] 2021-09-12 14:15
@bentolor thanks for the quick feedback. I am trying to use the docker compose ecs features which are in 20. It allows to call docker compose up on an ecs cluster and it will do all the right things to update the deployment. See here https://docs.docker.com/cloud/ecs-integration/

**Comment by bentolor** [comment] 2021-10-15 08:49
Thanks, @Foovanadil for pointing that out to me. I really didn't fully grasped the issue in the first run.
